<?php

namespace AmEveryWhere\Modules\ImageSeo;

/**
 * ImageAltAudit: REST endpoints for auditing and bulk-repairing missing
 * alt text in the WordPress media library.
 *
 * Complements ImageSeoModule (which handles uploads and post saves) by
 * providing retroactive repair of images already in the library.
 */
class ImageAltAudit
{
    public function register(): void
    {
        add_action('rest_api_init', [$this, 'registerRoutes']);
    }

    public function registerRoutes(): void
    {
        // GET: paginated list of images with missing alt text
        register_rest_route('ameverywhere/v1', '/images/missing-alt', [
            'methods'             => \WP_REST_Server::READABLE,
            'callback'            => [$this, 'getMissingAlt'],
            'permission_callback' => fn() => current_user_can('upload_files'),
            'args'                => [
                'page'     => ['default' => 1,  'sanitize_callback' => 'absint'],
                'per_page' => ['default' => 50, 'sanitize_callback' => 'absint'],
            ],
        ]);

        // POST: batch-update alt text [{id, alt}, ...]
        register_rest_route('ameverywhere/v1', '/images/bulk-alt', [
            'methods'             => \WP_REST_Server::CREATABLE,
            'callback'            => [$this, 'bulkUpdateAlt'],
            'permission_callback' => fn() => current_user_can('upload_files'),
        ]);

        // POST: auto-fill missing alt text from filenames (non-destructive)
        register_rest_route('ameverywhere/v1', '/images/auto-fill-alt', [
            'methods'             => \WP_REST_Server::CREATABLE,
            'callback'            => [$this, 'autoFillAlt'],
            'permission_callback' => fn() => current_user_can('upload_files'),
        ]);

        // BL-007: fix keyword mismatches in autogenerated alt text
        register_rest_route('ameverywhere/v1', '/images/fix-keyword-alt', [
            'methods'             => \WP_REST_Server::CREATABLE,
            'callback'            => [$this, 'fixKeywordAlt'],
            'permission_callback' => fn() => current_user_can('upload_files'),
        ]);
    }

    /**
     * Paginated list of image attachments missing or having empty alt text.
     * BL-007: Items include keyword_mismatch and focus_keyword fields.
     */
    public function getMissingAlt(\WP_REST_Request $request): \WP_REST_Response
    {
        $page    = max(1, (int) $request->get_param('page'));
        $perPage = min(200, max(1, (int) $request->get_param('per_page')));

        $query = new \WP_Query([
            'post_type'      => 'attachment',
            'post_status'    => 'inherit',
            'post_mime_type' => ['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/svg+xml'],
            'posts_per_page' => $perPage,
            'paged'          => $page,
            'meta_query'     => [
                'relation' => 'OR',
                ['key' => '_wp_attachment_image_alt', 'compare' => 'NOT EXISTS'],
                ['key' => '_wp_attachment_image_alt', 'value' => '', 'compare' => '='],
            ],
        ]);

        $items = [];
        foreach ($query->posts as $post) {
            $currentAlt = (string) get_post_meta($post->ID, '_wp_attachment_image_alt', true);
            $parentId   = (int) $post->post_parent;
            $keyword    = $parentId > 0 ? (string) get_post_meta($parentId, '_ameverywhere_focus_keyword', true) : '';

            // BL-007: null = no keyword configured, true = keyword missing from alt, false = ok
            if ($keyword === '') {
                $keywordMismatch = null;
            } else {
                $keywordMismatch = !empty($currentAlt) && stripos($currentAlt, $keyword) === false;
            }

            $items[] = [
                'id'               => $post->ID,
                'title'            => $post->post_title,
                'filename'         => basename((string) get_attached_file($post->ID)),
                'url'              => wp_get_attachment_url($post->ID),
                'thumb'            => wp_get_attachment_image_url($post->ID, 'thumbnail'),
                'alt'              => $currentAlt,
                'focus_keyword'    => $keyword,
                'keyword_mismatch' => $keywordMismatch,
            ];
        }

        return rest_ensure_response([
            'items'       => $items,
            'total'       => (int) $query->found_posts,
            'total_pages' => (int) $query->max_num_pages,
            'page'        => $page,
            'per_page'    => $perPage,
        ]);
    }

    /**
     * BL-007: Prepend focus keyword to autogenerated alt text for images
     * whose alt does not yet contain the parent post's focus keyword.
     * Manually-set alt text (no _ameverywhere_alt_autogenerated flag) is never touched.
     */
    public function fixKeywordAlt(\WP_REST_Request $request): \WP_REST_Response
    {
        $params = $request->get_json_params();
        $ids    = array_map('absint', $params['ids'] ?? []);
        $fixed  = 0;

        if (empty($ids)) {
            $query = new \WP_Query([
                'post_type'      => 'attachment',
                'post_status'    => 'inherit',
                'post_mime_type' => ['image/jpeg', 'image/png', 'image/gif', 'image/webp'],
                'posts_per_page' => 200,
                'fields'         => 'ids',
            ]);
            $ids = $query->posts;
        }

        foreach ($ids as $id) {
            $parentId = (int) (get_post($id)?->post_parent ?? 0);
            if ($parentId <= 0) {
                continue;
            }

            $keyword = (string) get_post_meta($parentId, '_ameverywhere_focus_keyword', true);
            if (empty($keyword)) {
                continue;
            }

            $isAutogenerated = get_post_meta($id, '_ameverywhere_alt_autogenerated', true);
            $currentAlt      = (string) get_post_meta($id, '_wp_attachment_image_alt', true);

            // Never overwrite manually-set alt text
            if (!empty($currentAlt) && $isAutogenerated !== 'yes') {
                continue;
            }

            // Already contains the keyword
            if (!empty($currentAlt) && stripos($currentAlt, $keyword) !== false) {
                continue;
            }

            $newAlt = mb_strimwidth($keyword . ' - ' . $currentAlt, 0, 125, '');
            update_post_meta($id, '_wp_attachment_image_alt', $newAlt);
            update_post_meta($id, '_ameverywhere_alt_autogenerated', 'yes');
            $fixed++;
        }

        return rest_ensure_response(['success' => true, 'fixed' => $fixed]);
    }

    /**
     * Batch-update alt text.
     * Payload: { "items": [{ "id": 123, "alt": "My description" }, ...] }
     */
    public function bulkUpdateAlt(\WP_REST_Request $request): \WP_REST_Response
    {
        $params = $request->get_json_params();
        $items  = $params['items'] ?? [];

        if (empty($items) || !is_array($items)) {
            return new \WP_REST_Response(['success' => false, 'message' => 'No items provided.'], 400);
        }

        $updated = 0;
        $errors  = [];

        foreach ($items as $item) {
            $id  = absint($item['id'] ?? 0);
            $alt = sanitize_text_field($item['alt'] ?? '');

            if ($id <= 0) {
                continue;
            }

            $attachment = get_post($id);
            if (!$attachment || $attachment->post_type !== 'attachment') {
                $errors[] = $id;
                continue;
            }

            update_post_meta($id, '_wp_attachment_image_alt', $alt);
            $updated++;
        }

        return rest_ensure_response(['success' => true, 'updated' => $updated, 'errors' => $errors]);
    }

    /**
     * Auto-fill missing alt text from filenames (non-destructive —
     * only processes images that currently have no alt text).
     */
    public function autoFillAlt(\WP_REST_Request $request): \WP_REST_Response
    {
        $params  = $request->get_json_params();
        $ids     = array_map('absint', $params['ids'] ?? []);
        $updated = 0;

        if (empty($ids)) {
            $query = new \WP_Query([
                'post_type'      => 'attachment',
                'post_status'    => 'inherit',
                'post_mime_type' => ['image/jpeg', 'image/png', 'image/gif', 'image/webp'],
                'posts_per_page' => 500,
                'meta_query'     => [
                    'relation' => 'OR',
                    ['key' => '_wp_attachment_image_alt', 'compare' => 'NOT EXISTS'],
                    ['key' => '_wp_attachment_image_alt', 'value' => '', 'compare' => '='],
                ],
            ]);
            $ids = wp_list_pluck($query->posts, 'ID');
        }

        foreach ($ids as $id) {
            $existing = get_post_meta($id, '_wp_attachment_image_alt', true);
            if (!empty($existing)) {
                continue;
            }

            $file    = (string) get_attached_file($id);
            $altText = $this->cleanFilename(pathinfo($file, PATHINFO_FILENAME));

            if (!empty($altText)) {
                update_post_meta($id, '_wp_attachment_image_alt', $altText);
                $updated++;
            }
        }

        return rest_ensure_response(['success' => true, 'updated' => $updated]);
    }

    /** "my-awesome_photo-2024" → "My Awesome Photo 2024" */
    private function cleanFilename(string $filename): string
    {
        $cleaned = preg_replace('/-\d+x\d+$/', '', $filename) ?? $filename;
        $cleaned = str_replace(['-', '_', '.'], ' ', $cleaned);
        $cleaned = preg_replace('/\s+/', ' ', $cleaned) ?? $cleaned;
        return ucwords(trim($cleaned));
    }
}
